# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Telegram Creative"
description: > # this means to ignore newlines until "email:"
   A blog about creating things.

email: telegramco@gmail.com

# Circular logo on homepage
homepage_logo: "/assets/images/logo-circle-creative-gold-600.png"

# Blog logo in upper-left corner (and other places)
logo: "/assets/images/logo-square-noborder-400.png"

# Blog cover image
cover: "/assets/images/typewriter.jpg"

name: 'Michael Ashton'
author: 'Michael Ashton'

paginate:	5

url: "http://telegram-creative.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	tumblr
    url:	http://telegramco.tumblr.com
    desc: Follow us on Tumblr
    #share_url: //www.tumblr.com/share/link
    #share_title: ?name=
    #share_link: "&amp;url="

  - icon:	instagram
    url:	http://instagram.com/telegram_co
    desc: Follow us on Instagram

  - icon:	facebook
    url:	https://www.facebook.com/telegramco
    desc: Connect with us on Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	twitter
    url:	https://twitter.com/telegram_co
    desc: Follow us on Twitter
    share_url: //twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
